### ISSUE TITLE
进程不支持异步协程

### ISSUE THREAD

**Issue by Nenot233** [Agnes4m/nonebot_plugin_bilifan#1]

**Comment by Agnes4m** [comment]
执行的时候是有问题，我本地修改了还没有上传pypi(悲

**Comment by Nenot233** [comment]
修复了路径，但是b站登录无法触发（无二维码发送）

**Comment by Nenot233** [comment]
哦原来是用了这个指令如果一直没登录就会卡住，导致阻塞

**Comment by Agnes4m** [comment]
> 哦原来是用了这个指令如果一直没登录就会卡住，导致阻塞

对的，因为还是同步的，不是异步的。

**Comment by Nenot233** [comment]
但是这个群友一刷，但是又不登录，就会导致进程卡死，需要手动重启才能复活，所以有解决方案吗？
