### ISSUE TITLE
源码已修复点赞，是否考虑更新

### ISSUE THREAD

**Issue by Nenot233** [Agnes4m/nonebot_plugin_bilifan#12]
https://github.com/XiaoMiku01/fansMedalHelper/commit/9772d1392d4572e5201443597dc17e5800a7a912

**Comment by Agnes4m** [comment]
好好，明天不加班就更

**Comment by Agnes4m** [comment]
还是连夜更 了，把 之前的bug也修复了

**Comment by Nenot233** [comment]
10-30 09:18:14 [ERROR] nonebot | Failed to import "nonebot_plugin_bilifan"
Traceback (most recent call last):
  File "D:\BOT\zhenxun_bot\bot.py", line 16, in <module>
    nonebot.load_plugins("extensive_plugin")
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 48, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
 File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 241, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_bilifan\__init__.py", line 10, in <module>
    from nonebot.plugin import PluginMetadata, inherit_supported_adapters
ImportError: cannot import name 'inherit_supported_adapters' from 'nonebot.plugin' (C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\__init__.py)

PS D:\BOT\zhenxun_bot> pip list
Package                               Version
------------------------------------- ---------------
absl-py                               1.4.0
addict                                2.4.0
aiocache                              0.12.1
aiocqhttp                             1.4.4
aiofiles                              23.1.0
aiohttp                               3.8.4
aiosignal                             1.3.1
aiosqlite                             0.17.0
alembic                               1.11.1
amis-python                           1.0.8.post2
annotated-types                       0.5.0
anyio                                 3.7.1
APScheduler                           3.10.1
argon2-cffi                           21.3.0
argon2-cffi-bindings                  21.2.0
arrow                                 1.2.3
asttokens                             2.2.1
astunparse                            1.6.3
async-timeout                         4.0.2
asyncmy                               0.2.8
asyncodbc                             0.1.1
asyncpg                               0.28.0
atlastk                               0.13.2
attrs                                 23.1.0
backcall                              0.2.0
baike                                 1.5.0
basicsr                               1.4.2
bbcode                                1.1.0
beautifulsoup4                        4.12.2
bilireq                               0.2.6
bleach                                6.0.0
blinker                               1.6.2
build                                 0.10.0
CacheControl                          0.12.14
cachetools                            5.3.1
cattrs                                23.1.2
certifi                               2023.5.7
cffi                                  1.15.1
chardet                               5.1.0
charset-normalizer                    3.2.0
cleo                                  2.0.1
click                                 8.1.4
cn2an                                 0.5.20
colorama                              0.4.6
comm                                  0.1.3
contourpy                             1.1.0
crashtest                             0.4.1
cssselect                             1.2.0
cycler                                0.11.0
Cython                                3.0.0
dateparser                            1.1.8
debugpy                               1.6.7
decorator                             5.1.1
defusedxml                            0.7.1
diskcache                             5.6.1
distlib                               0.3.6
docopt                                0.6.2
dulwich                               0.21.5
ecdsa                                 0.18.0
efinance                              0.5.0
emoji                                 2.6.0
exceptiongroup                        1.1.2
executing                             1.2.0
facexlib                              0.3.0
fastapi                               0.100.0
fastjsonschema                        2.17.1
feedparser                            6.0.10
filelock                              3.12.2
filetype                              1.2.0
filterpy                              1.4.5
Flask                                 2.3.2
flatbuffers                           23.5.26
fonttools                             4.40.0
fqdn                                  1.5.1
frozenlist                            1.3.3
fsspec                                2023.6.0
future                                0.18.3
fuzzywuzzy                            0.18.0
gast                                  0.4.0
gensim                                4.3.1
gfpgan                                1.3.8
google-api-core                       2.11.1
google-auth                           2.21.0
google-auth-oauthlib                  1.0.0
google-cloud                          0.34.0
google-cloud-vision                   3.4.4
google-pasta                          0.2.0
googleapis-common-protos              1.59.1
greenlet                              2.0.2
grpcio                                1.56.0
grpcio-status                         1.56.0
h11                                   0.14.0
h2                                    4.1.0
h5py                                  3.9.0
hpack                                 4.0.0
html5lib                              1.1
httpcore                              0.17.3
httptools                             0.6.0
httpx                                 0.24.1
huggingface-hub                       0.16.4
hypercorn                             0.14.4
hyperframe                            6.0.1
idna                                  3.4
ImageHash                             4.3.1
imageio                               2.31.1
imagetext_py                          2.1.3
importlib-metadata                    6.8.0
inaSpeechSegmenter                    0.7.6
installer                             0.7.0
ipykernel                             6.24.0
ipython                               8.14.0
ipython-genutils                      0.2.0
ipywidgets                            8.0.7
iso8601                               1.1.0
isoduration                           20.11.0
itsdangerous                          2.1.2
jaraco.classes                        3.3.0
jedi                                  0.18.2
jieba                                 0.42.1
Jinja2                                3.1.2
joblib                                1.3.1
jsonpath                              0.82
jsonpointer                           2.4
jsonschema                            4.18.0
jsonschema-specifications             2023.6.1
jupyter                               1.0.0
jupyter_client                        8.3.0
jupyter-console                       6.6.3
jupyter_core                          5.3.1
jupyter-events                        0.6.3
jupyter_server                        2.7.0
jupyter_server_terminals              0.4.4
jupyterlab-pygments                   0.2.2
jupyterlab-widgets                    3.0.8
keras                                 2.13.1
keyring                               23.13.1
kiwisolver                            1.4.4
langid                                1.1.6
lazy_loader                           0.3
libclang                              16.0.0
llvmlite                              0.41.1
lmdb                                  1.4.1
lockfile                              0.12.2
loguru                                0.6.0
lxml                                  4.9.3
Mako                                  1.2.4
Markdown                              3.4.3
markdown-it-py                        3.0.0
MarkupSafe                            2.1.3
matplotlib                            3.7.2
matplotlib-inline                     0.1.6
mdurl                                 0.1.2
meme-generator                        0.0.13
mistune                               3.0.1
more-itertools                        9.1.0
mpmath                                1.3.0
msgpack                               1.0.5
multidict                             6.0.4
multitasking                          0.0.11
munkres                               1.1.4
nbclassic                             1.0.0
nbclient                              0.8.0
nbconvert                             7.6.0
nbformat                              5.9.0
nest-asyncio                          1.5.6
networkx                              3.1
nonebot                               1.9.1
nonebot-adapter-onebot                2.2.3
nonebot-plugin-apscheduler            0.3.0
nonebot-plugin-datastore              1.1.0
nonebot-plugin-guild-patch            0.2.3
nonebot-plugin-htmlrender             0.2.1
nonebot-plugin-imageutils             0.1.17
nonebot-plugin-localstore             0.5.0
nonebot-plugin-send-anything-anywhere 0.3.2
nonebot-plugin-sendmsg-by-bots        0.0.4
nonebot-plugin-session                0.1.0
nonebot-plugin-tortoise-orm           0.1.1
nonebot2                              2.0.0
notebook                              6.5.4
notebook_shim                         0.2.3
numba                                 0.58.1
numpy                                 1.24.3
oauthlib                              3.2.2
openai                                0.27.8
opencv-python                         4.8.0.74
opencv-python-headless                4.8.0.74
opt-einsum                            3.3.0
overrides                             7.3.1
packaging                             23.1
pandas                                2.0.3
pandocfilters                         1.5.0
parso                                 0.8.3
peewee                                3.16.2
pexpect                               4.8.0
picimagesearch                        3.9.2
pickleshare                           0.7.5
pil-utils                             0.1.7
Pillow                                9.5.0
pip                                   23.3
pkginfo                               1.9.6
platformdirs                          3.8.1
playwright                            1.35.0
poetry                                1.5.1
poetry-core                           1.6.1
poetry-plugin-export                  1.4.0
prettytable                           3.8.0
priority                              2.0.0
proces                                0.1.4
prometheus-client                     0.17.0
prompt-toolkit                        3.0.39
proto-plus                            1.22.3
protobuf                              4.23.4
psutil                                5.9.5
ptyprocess                            0.7.0
pure-eval                             0.2.2
py                                    1.11.0
pyannote.algorithms                   0.8
pyannote.core                         5.0.0
pyannote.parser                       0.8
pyasn1                                0.5.0
pyasn1-modules                        0.3.0
pycparser                             2.21
pydantic                              1.10.12
pydantic_core                         2.6.3
pydub                                 0.25.1
pyee                                  9.0.4
Pygments                              2.15.1
pygtrie                               2.5.0
pymdown-extensions                    10.0.1
pyodbc                                5.0.1
pyparsing                             3.0.9
pypika-tortoise                       0.1.6
pypinyin                              0.49.0
pypng                                 0.20220715.0
pyproject_hooks                       1.0.0
pyquery                               2.0.0
Pyro4                                 4.82
pytextgrid                            0.1.4
python-dateutil                       2.8.2
python-dotenv                         1.0.0
python-jose                           3.3.0
python-json-logger                    2.0.7
python-markdown-math                  0.8
python-multipart                      0.0.5
pytz                                  2023.3
PyWavelets                            1.4.1
pywin32                               306
pywin32-ctypes                        0.2.2
pywinpty                              2.0.10
PyYAML                                6.0
pyzbar                                0.1.9
pyzmq                                 25.1.0
qrcode                                7.4.2
qtconsole                             5.4.3
QtPy                                  2.3.1
quart                                 0.18.4
rapidfuzz                             2.15.1
realesrgan                            0.3.0
referencing                           0.29.1
regex                                 2023.6.3
requests                              2.31.0
requests-oauthlib                     1.3.1
requests-toolbelt                     1.0.0
retry                                 0.9.2
retrying                              1.3.4
rfc3339-validator                     0.1.4
rfc3986                               1.5.0
rfc3986-validator                     0.1.1
rich                                  13.4.2
rpds-py                               0.8.10
rsa                                   4.9
ruamel.yaml                           0.17.32
ruamel.yaml.clib                      0.2.7
safetensors                           0.3.1
scikit-image                          0.21.0
scikit-learn                          1.3.0
scipy                                 1.11.1
Send2Trash                            1.8.2
serpent                               1.41
setuptools                            65.5.0
sgmllib3k                             1.0.0
ShazamAPI                             0.0.2
shellingham                           1.5.0.post1
six                                   1.16.0
smart-open                            6.3.0
sniffio                               1.3.0
sortedcollections                     2.1.0
sortedcontainers                      2.4.0
soundfile                             0.12.1
soupsieve                             2.4.1
SQLAlchemy                            2.0.18
stack-data                            0.6.2
starlette                             0.27.0
StrEnum                               0.4.15
sympy                                 1.12
tb-nightly                            2.15.0a20231019
tenacity                              8.2.2
tensorboard                           2.13.0
tensorboard-data-server               0.7.1
tensorflow                            2.13.0
tensorflow-estimator                  2.13.0
tensorflow-intel                      2.13.0
tensorflow-io-gcs-filesystem          0.31.0
termcolor                             2.3.0
terminado                             0.17.1
thefuzz                               0.19.0
threadpoolctl                         3.1.0
tifffile                              2023.7.4
tinycss2                              1.2.1
tinydb                                4.8.0
tokenizers                            0.12.1
toml                                  0.10.2
tomli                                 2.0.1
tomlkit                               0.11.8
torch                                 2.1.0
torchvision                           0.16.0
tornado                               6.3.2
tortoise                              0.1.1
tortoise-orm                          0.19.3
tqdm                                  4.65.0
traitlets                             5.9.0
transformers                          4.30.2
trove-classifiers                     2023.7.6
typing_extensions                     4.7.1
tzdata                                2023.3
tzlocal                               5.0.1
ua-parser                             0.18.0
ujson                                 5.8.0
uri-template                          1.3.0
urllib3                               1.26.16
user-agents                           2.2.0
uvicorn                               0.22.0
virtualenv                            20.23.1
watchfiles                            0.19.0
wcwidth                               0.2.6
webcolors                             1.13
webencodings                          0.5.1
websocket-client                      1.6.1
websockets                            11.0.3
wenxin-api                            0.2.1
Werkzeug                              2.3.6
wheel                                 0.40.0
widgetsnbextension                    4.0.8
win32-setctime                        1.1.0
wordcloud                             1.9.2
wrapt                                 1.15.0
wsproto                               1.2.0
xarray                                2023.6.0
yapf                                  0.40.2
yarl                                  1.9.2
zipp                                  3.16.0
WARNING: There was an error checking the latest version of pip.
加载失败，是依赖或者是版本的问题吗？

**Comment by Nenot233** [comment]
已经自行修复加载问题，点赞任务还是异常
10-30 10:37:02 [ERROR] nonebot_plugin_bilifan | 点赞任务异常
Traceback (most recent call last):
  File "D:\BOT\zhenxun_bot\bot.py", line 22, in <module>
    nonebot.run()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 201, in run
    uvicorn.run(
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
 File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_bilifan\src\user.py", line 241, in like_v3
    await asyncio.gather(*allTasks)
  File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_bilifan\src\api.py", line 205, in likeInteractV3
    await self.__post(
  File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_bilifan\src\api.py", line 68, in wrapper
    raise E  # noqa: TRY201
  File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_bilifan\src\api.py", line 57, in wrapper
    result = await func(*args, **kwargs)
  File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_bilifan\src\api.py", line 133, in __post
    return self.__check_response(await resp.json())
  File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_bilifan\src\api.py", line 122, in __check_response
    raise BiliApiError(resp["code"], resp["message"])
extensive_plugin.nonebot_plugin_bilifan.src.api.BiliApiError: Key: 'LikeReportV3Req.ClickTime' Error:Field validation for 'ClickTime' failed on the 'required' tag

**Comment by Agnes4m** [comment]
已修复，版本号0.3.0-post1
