### ISSUE TITLE
user.yaml

### ISSUE THREAD

**Issue by Healock** [Agnes4m/nonebot_plugin_bilifan#3]
WATCHINGLIVE: 2 # 每日观看直播时长，单位 min ，设置为0则关闭, 默认 65 分钟

此参数应调为65或以上，否则出现只获得200亲密度的情况。
源于 fansMedalHelper 某次更新时此参数未作过渡调整，导致旧版本参数不适配新版本。

**Comment by Agnes4m** [comment]
感谢反馈，这里因为必须所有的任务结束bot才能返回输出，而默认65分钟我本认为太长了，会影响bot交互的体验，下个版本把直播观看的操作和其他操作分离返回输出。
