### ISSUE TITLE
最新版本B站登录显示聊天记录

### ISSUE THREAD

**Issue by Nenot233** [Agnes4m/nonebot_plugin_bilifan#8]
![3cd232a6ecb2243937d7eae523680bf](https://github.com/Agnes4m/nonebot_plugin_bilifan/assets/108965579/37adc848-b954-4d9c-bd81-b6768e9f5f96)

**Comment by Agnes4m** [comment]
已更新0.2.2，测试没问题
![image](https://github.com/Agnes4m/nonebot_plugin_bilifan/assets/70925546/0c4e4d93-5b3c-48bd-9262-92dd3459e400)
